[
  {"id":1,"name":"Laptop","price":55000,"category":"Electronics"},
  {"id":2,"name":"Smartphone","price":25000,"category":"Electronics"},
  {"id":3,"name":"Tablet","price":18000,"category":"Electronics"},
  {"id":4,"name":"Smart Watch","price":5000,"category":"Electronics"},
  {"id":5,"name":"Headphones","price":2500,"category":"Electronics"},
  {"id":6,"name":"Bluetooth Speaker","price":3200,"category":"Electronics"},
  {"id":7,"name":"Keyboard","price":1500,"category":"Accessories"},
  {"id":8,"name":"Mouse","price":800,"category":"Accessories"},
  {"id":9,"name":"Webcam","price":2200,"category":"Electronics"},
  {"id":10,"name":"Power Bank","price":1800,"category":"Electronics"},

  {"id":11,"name":"Backpack","price":1200,"category":"Bags"},
  {"id":12,"name":"Travel Bag","price":2500,"category":"Bags"},
  {"id":13,"name":"Wallet","price":900,"category":"Fashion"},
  {"id":14,"name":"Handbag","price":1800,"category":"Fashion"},
  {"id":15,"name":"Sunglasses","price":1500,"category":"Fashion"},
  {"id":16,"name":"Watch","price":3500,"category":"Fashion"},
  {"id":17,"name":"Cap","price":500,"category":"Fashion"},
  {"id":18,"name":"Belt","price":700,"category":"Fashion"},
  {"id":19,"name":"Shoes","price":2800,"category":"Fashion"},
  {"id":20,"name":"T-Shirt","price":700,"category":"Clothing"},

  {"id":21,"name":"Jeans","price":1800,"category":"Clothing"},
  {"id":22,"name":"Jacket","price":3200,"category":"Clothing"},
  {"id":23,"name":"Hoodie","price":2200,"category":"Clothing"},
  {"id":24,"name":"Shirt","price":1200,"category":"Clothing"},
  {"id":25,"name":"Track Pants","price":1000,"category":"Clothing"},
  {"id":26,"name":"Shorts","price":800,"category":"Clothing"},
  {"id":27,"name":"Sweater","price":1600,"category":"Clothing"},
  {"id":28,"name":"Socks","price":300,"category":"Clothing"},
  {"id":29,"name":"Scarf","price":600,"category":"Clothing"},
  {"id":30,"name":"Gloves","price":500,"category":"Clothing"},

  {"id":31,"name":"Notebook","price":120,"category":"Stationery"},
  {"id":32,"name":"Pen","price":20,"category":"Stationery"},
  {"id":33,"name":"Pencil","price":10,"category":"Stationery"},
  {"id":34,"name":"Eraser","price":10,"category":"Stationery"},
  {"id":35,"name":"Marker","price":50,"category":"Stationery"},
  {"id":36,"name":"Geometry Box","price":150,"category":"Stationery"},
  {"id":37,"name":"Calculator","price":500,"category":"Stationery"},
  {"id":38,"name":"Diary","price":250,"category":"Stationery"},
  {"id":39,"name":"Sticky Notes","price":80,"category":"Stationery"},
  {"id":40,"name":"File Folder","price":100,"category":"Stationery"},

  {"id":41,"name":"Water Bottle","price":600,"category":"Home"},
  {"id":42,"name":"Coffee Mug","price":300,"category":"Home"},
  {"id":43,"name":"Dinner Plate","price":150,"category":"Kitchen"},
  {"id":44,"name":"Glass Set","price":400,"category":"Kitchen"},
  {"id":45,"name":"Frying Pan","price":900,"category":"Kitchen"},
  {"id":46,"name":"Cooker","price":1800,"category":"Kitchen"},
  {"id":47,"name":"Knife Set","price":700,"category":"Kitchen"},
  {"id":48,"name":"Cutting Board","price":350,"category":"Kitchen"},
  {"id":49,"name":"Lunch Box","price":500,"category":"Kitchen"},
  {"id":50,"name":"Electric Kettle","price":1400,"category":"Kitchen"},

  {"id":51,"name":"Table Lamp","price":900,"category":"Home"},
  {"id":52,"name":"Wall Clock","price":700,"category":"Home"},
  {"id":53,"name":"Cushion","price":400,"category":"Home"},
  {"id":54,"name":"Bedsheet","price":1200,"category":"Home"},
  {"id":55,"name":"Pillow","price":600,"category":"Home"},
  {"id":56,"name":"Curtains","price":1800,"category":"Home"},
  {"id":57,"name":"Floor Mat","price":500,"category":"Home"},
  {"id":58,"name":"Mirror","price":1000,"category":"Home"},
  {"id":59,"name":"Flower Vase","price":450,"category":"Home"},
  {"id":60,"name":"Desk Organizer","price":350,"category":"Home"},

  {"id":61,"name":"Football","price":900,"category":"Sports"},
  {"id":62,"name":"Cricket Bat","price":2500,"category":"Sports"},
  {"id":63,"name":"Cricket Ball","price":250,"category":"Sports"},
  {"id":64,"name":"Badminton Racket","price":1200,"category":"Sports"},
  {"id":65,"name":"Tennis Racket","price":2200,"category":"Sports"},
  {"id":66,"name":"Basketball","price":1000,"category":"Sports"},
  {"id":67,"name":"Skipping Rope","price":300,"category":"Fitness"},
  {"id":68,"name":"Yoga Mat","price":700,"category":"Fitness"},
  {"id":69,"name":"Dumbbells","price":1500,"category":"Fitness"},
  {"id":70,"name":"Gym Gloves","price":500,"category":"Fitness"},

  {"id":71,"name":"Face Wash","price":350,"category":"Beauty"},
  {"id":72,"name":"Shampoo","price":450,"category":"Beauty"},
  {"id":73,"name":"Conditioner","price":400,"category":"Beauty"},
  {"id":74,"name":"Body Lotion","price":300,"category":"Beauty"},
  {"id":75,"name":"Face Cream","price":500,"category":"Beauty"},
  {"id":76,"name":"Lip Balm","price":150,"category":"Beauty"},
  {"id":77,"name":"Perfume","price":1200,"category":"Beauty"},
  {"id":78,"name":"Hair Oil","price":250,"category":"Beauty"},
  {"id":79,"name":"Comb","price":100,"category":"Beauty"},
  {"id":80,"name":"Makeup Kit","price":1800,"category":"Beauty"},

  {"id":81,"name":"Novel","price":500,"category":"Books"},
  {"id":82,"name":"Programming Book","price":900,"category":"Books"},
  {"id":83,"name":"Dictionary","price":600,"category":"Books"},
  {"id":84,"name":"Story Book","price":350,"category":"Books"},
  {"id":85,"name":"Notebook Set","price":300,"category":"Books"},
  {"id":86,"name":"Art Book","price":700,"category":"Books"},
  {"id":87,"name":"Science Book","price":800,"category":"Books"},
  {"id":88,"name":"Math Book","price":750,"category":"Books"},
  {"id":89,"name":"History Book","price":650,"category":"Books"},
  {"id":90,"name":"English Book","price":550,"category":"Books"},

  {"id":91,"name":"USB Cable","price":300,"category":"Accessories"},
  {"id":92,"name":"Charger","price":900,"category":"Accessories"},
  {"id":93,"name":"HDMI Cable","price":500,"category":"Accessories"},
  {"id":94,"name":"Memory Card","price":700,"category":"Accessories"},
  {"id":95,"name":"USB Drive","price":600,"category":"Accessories"},
  {"id":96,"name":"Phone Stand","price":350,"category":"Accessories"},
  {"id":97,"name":"Laptop Stand","price":1200,"category":"Accessories"},
  {"id":98,"name":"Screen Protector","price":250,"category":"Accessories"},
  {"id":99,"name":"Phone Cover","price":400,"category":"Accessories"},
  {"id":100,"name":"Wireless Charger","price":1500,"category":"Accessories"}
]